---
- name: Install builders packages
  hosts: build
  become: true

  tasks:
    - name: Install maven & git packages
      apt:
        pkg:
        - maven
        - git
        state: present
    
    - name: Get source code of artefact
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/box

    - name: Building artefact
      shell: mvn clean install
      become: true
      args:
        chdir: /tmp/box
          
    - name: Copy artefact to prod
      synchronize:
        src: /tmp/box/target/*.war
        dest: rsync://prod/tmp/
      delegate_to: build


#- name: Install prod packages & start artefact
#  hosts: prod
#  become: true
#
#  tasks:
#    - name: Install tomcat & java
#      apt:
#        pkg:
#        - tomcat
#        - default-jdk
#        state: present
#
#    - name: Ensure tomcat is started
#      service: 
#        name: tomcat
#        state: started
#    
#    - name: Move artefact to tomcat
#      copy:
#        src: /tmp/*.war
#        dest: /var/lib/tomcat*/webapps