---
- name: Install builders packages
  hosts: build
  become: true

  tasks:
    - name: Install maven & git packages
      apt:
        pkg:
        - maven
        - git
        state: present
    
    - name: Building artefact


    - name: Copy artefact to prod
      copy:
        src: boxfuse-*/target/*.war
        dest: prod:/tmp


- name: Install prod packages & start artefact
  hosts: prod
  become: true

  tasks:
    - name: Install tomcat & java
      apt:
        pkg:
        - tomcat
        - default-jdk
        state: present

    - name: Ensure tomcat is started
      service: 
        name: tomcat
        state: started
    
    - name: Move artefact to tomcat
      copy:
        src: /tmp/*.war
        dest: /var/lib/tomcat*/webapps

