---
- name: Install builders packages
  hosts: build
  become: true

  tasks:
    - name: Install maven & git packages
      apt:
        pkg:
        - maven
        - git
        state: present
    
    - name: Get source code of artefact
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/box

    - name: Building artefact
      shell: mvn clean install
      become: true
      args:
        chdir: /tmp/box
          
    - name: Copy artefact from build server to control server
      become: true
      synchronize:
        mode: pull
        src: /tmp/box/target/*.war
        dest: /etc/ansible/


- name: Install prod packages & start artefact
  hosts: prod
  become: true

  tasks:
    - name: Install tomcat & java
      apt:
        pkg:
        - tomcat9
        - default-jdk
        state: present

    - name: Ensure tomcat is started
      service: 
        name: tomcat9
        state: started
    
    - name: Copy artefact to tomcat
      become: true
      synchronize:
        src: ./hello*.war
        dest: /var/lib/tomcat*/webapps/